import { StudentAdmissionFees } from "../components/AdmissionProcess/StudentAdmissionFees";
import PrivacyPolicy from "../components/Privacy/Privacy";

export const allRouterLink = {
    homeScreen: "/",
    registerUser: "/register",
    loginUser: "/login",
    changePassword: "/changePassword",
    forgotPassword: "/forgotPassword",
    resetPassword: "/resetPassword",
    admissionForm: "/admissionForm",
    admissionFees: "/admissionFees/",
    studentFeeCard: "/studentFeeCard/:student_id",
    documentUpload: "/documentUpload",
    viewDocuments: "/viewDocuments",
    TimeTable: "/TimeTable",
    subjectAssignment: "/subjectAssignment",
    ClassTeacherAssign: "/ClassTeacherAssign",
    ViewAllocatedClass: "/ViewAllocatedClass",
    allTeacherAssignment: "/allTeacherAssignment",
    attendance: "/attendance",
    SingleTeacher: "/SingleTeacher",
    ExamSchedule: "/ExamSchedule",
    UpdateExamSchedule: "/UpdateExamSchedule",
    UploadExamPaper: "/UploadExamPaper",
    classStudents: "/classStudents/:classLevel/:Year_level_id",
    directorProfile: '/directorProfile',
    officeStaffProfile: '/officeStaffProfile',
    guardianProfile: '/guardianProfile',
    teacherProfile: '/teacherProfile',
    MarksheetsTable: '/MarksheetsTable',
    studentProfile: '/studentProfile',
    teacherDashboard: '/teacherDashboard',
    guardianDashboard: '/guardianDashboard',
    studentDashboard: '/studentDashboard',
    guardianAttendanceRecord: '/guardianAttendanceRecord',
    studentAttendance: '/studentAttendance',
    directorDashboard: '/directorDashboard',
    feeSummary: '/feeSummary',
    ViewExamPaper: '/ViewExamPaper',
    HolidayCalendar: '/HolidayCalendar',
    UpdateExamPaper: '/UpdateExamPaper',
    StudentMarksFill: '/StudentMarksFill',
    feeDashboard: '/feeDashboard',
    createDiscount: '/createDiscount',
    editDiscount: '/createDiscount/:id',
    attendanceRecord: '/attendanceRecord',
    fullAttendance: '/fullAttendance/:className',
    directorMarkHolidays: '/directorMarkHolidays',
    officeStaffDashboard: '/officeStaffDashboard',
    addmissionDetails: '/addmissionDetails',
    addmissionDetailsById: '/addmissionDetails/:id',
    editAddmisionDetails: '/editAddmisionDetails/:id',
    allClasses: '/allClasses',
    TeacherSubstitute: '/TeacherSubstitute',
    Marksheet: '/Marksheet/:id',
    allStudentsperClass: '/allStudentsPerClass/:id',
    studentDetails: '/studentDetails/:id',
    updateStudentdetail: '/updateStudentdetail/:id',
    allStaffMembers: '/allStaffMembers',
    staffDetail: '/staffDetail/:type/:id',
    updateStaffDetails: '/staffdetail/update/:type/:id',
    myAttendance: '/myAttendance/:id',
    periodsByClass: '/periodsByClass',
    periodAssignment: "periodAssignment/:year_level_id",
    guardianChildren: "/guardianChildren",
    overdueAccounts: "/overdueAccounts",
    createSalaryExpense: "/createSalaryExpense",
    viewSalaryExpense: "/viewSalaryExpense",
    viewAllExpenses: "/viewAllExpenses",
    createExpenses: "/createExpenses",
    editExpenses: "/editExpenses/:id",
    editSalaryExpense: "/editSalaryExpense/:id",
    paySalaryExpense: "/paySalaryExpense/:id",
    updateSalaryExpense: "/updateSalaryExpense/:id",
    employeeMonthySalary: "/employeeMonthySalary/:id",
    discountedStudents: "/discountedStudents",
    editStudentDiscount: "/editStudentDiscount/:id",
    teacherAttendance:"/teacherAttendance",
    teacherAttendanceRecord:"/teacherAttendanceRecord",
    schoolIncome: "/schoolIncome",
    createIncome: "/createIncome",
    editIncom:"/editIncom/:id",
    studentAdmissionFees:"/studentAdmissionFees/:id",
    privacyPolicy:"/privacyPolicy",
    createMarksheet:"/createMarksheet",

    // all routes before this
    unAuthorized: '/unauthorized',
    managecategory:"/managecategory",
    notFound: "*"
}